# Numpy assignment
- Different tasks will be detailed by comments or text.
- For further reference and resources, it's advised to check out the NumPy documentation.

In [1]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [2]:
# Create a 1-dimensional NumPy array using np.array()
b = np.array( [1,2,3,4])

# Create a 2-dimensional NumPy array using np.array()
x = np.array([[1,2,3,4],[3,4,5,6]])

In [3]:
# Attributes of 1-dimensional array (shape, number of dimensions, data type, size and type)
print("Shape: ",b.shape)
print("No of Dimensions: ",b.ndim)
print("Size: ",b.size)
print("Type: ",b.dtype)

Shape:  (4,)
No of Dimensions:  1
Size:  4
Type:  int32


In [4]:
# Attributes of 2-dimensional array
print("Shape: ",x.shape)
print("No of Dimensions: ",x.ndim)
print("Size: ",x.size)
print("Type: ",x.dtype)

Shape:  (2, 4)
No of Dimensions:  2
Size:  8
Type:  int32


In [5]:
# Create an array of shape (5, 5) with only ones
x = np.ones((5,5), np.int64)
x

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=int64)

In [6]:
# Create an array of shape (3, 3, 5) with only zeros
p = np.zeros((3,3,5),np.int64)
p

array([[[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]]], dtype=int64)

In [7]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
p1 = np.random.randint(0,10,(7,2), np.int64)
p1

array([[7, 2],
       [8, 8],
       [5, 5],
       [3, 7],
       [4, 5],
       [8, 9],
       [6, 4]], dtype=int64)

In [8]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
p2 = np.random.rand(3,5)
p2

array([[0.11000086, 0.95140032, 0.37928879, 0.31234413, 0.7480323 ],
       [0.67159905, 0.16992989, 0.84445439, 0.42919247, 0.96316457],
       [0.48468939, 0.33814715, 0.63080343, 0.5163436 , 0.97461641]])

In [9]:
# Create an array of normally distributed random numbers
b6 = np.random.randn(5)
b6

array([ 9.55301877e-01,  2.00206144e+00, -5.50408905e-04,  3.58405592e-03,
        9.66722444e-01])

In [10]:
# Set the random seed to 42
np.random.seed(42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
w = np.random.rand(4,6)
w

array([[0.37454012, 0.95071431, 0.73199394, 0.59865848, 0.15601864,
        0.15599452],
       [0.05808361, 0.86617615, 0.60111501, 0.70807258, 0.02058449,
        0.96990985],
       [0.83244264, 0.21233911, 0.18182497, 0.18340451, 0.30424224,
        0.52475643],
       [0.43194502, 0.29122914, 0.61185289, 0.13949386, 0.29214465,
        0.36636184]])

In [11]:
# Copy the code from the cell above and run it again
np.random.seed(42)
w = np.random.rand(4,6)
w

array([[0.37454012, 0.95071431, 0.73199394, 0.59865848, 0.15601864,
        0.15599452],
       [0.05808361, 0.86617615, 0.60111501, 0.70807258, 0.02058449,
        0.96990985],
       [0.83244264, 0.21233911, 0.18182497, 0.18340451, 0.30424224,
        0.52475643],
       [0.43194502, 0.29122914, 0.61185289, 0.13949386, 0.29214465,
        0.36636184]])

In [12]:
# Find the 0'th index of the latest array you created
print(w[0][0])

0.3745401188473625


In [13]:
# Get the first 2 rows of latest array you created
r1=w[0]
r2=w[1]
print(r1,"\n",r2)

[0.37454012 0.95071431 0.73199394 0.59865848 0.15601864 0.15599452] 
 [0.05808361 0.86617615 0.60111501 0.70807258 0.02058449 0.96990985]


In [14]:
# Get the first 2 values of the first 2 rows of the latest array
r1v1 = r1[0]
r2v1 = r2[0]
print(r1v1,"\n",r2v1)

0.3745401188473625 
 0.05808361216819946


In [16]:
# Create a random array of numbers between 0 & 10 and an array of ones both of size (3, 5), save them both to variables
q = np.random.randint(0,10,(3,5), np.int64)
q1 = np.ones((3,5), dtype= np.int64)


In [17]:
# Add the two arrays together
q2=q+q1

In [18]:
# Create another array of ones of shape (5, 3)
a4 = np.ones( (5,3), np.int64)

In [19]:
# Try add the array of ones and the other most recent array together # You can anticipate an error
a12=a4+q2

ValueError: operands could not be broadcast together with shapes (5,3) (3,5) 

In [20]:
# Do the same operation you just did but this time with a transpose on one array
a12 = q2 + np.transpose(a4)
a12

array([[11, 10, 11,  6,  3],
       [ 5,  8,  9,  4,  2],
       [ 5,  3,  9,  5,  3]], dtype=int64)

In [21]:
# Take the latest array to the power of 2 using the python way
w**2

array([[1.40280301e-01, 9.03857692e-01, 5.35815131e-01, 3.58391981e-01,
        2.43418162e-02, 2.43342904e-02],
       [3.37370600e-03, 7.50261116e-01, 3.61339257e-01, 5.01366775e-01,
        4.23721405e-04, 9.40725121e-01],
       [6.92960750e-01, 4.50878979e-02, 3.30603187e-02, 3.36372142e-02,
        9.25633424e-02, 2.75369313e-01],
       [1.86576499e-01, 8.48144121e-02, 3.74363965e-01, 1.94585372e-02,
        8.53484957e-02, 1.34221000e-01]])

In [22]:
# Do the same thing with numpy way
np.power(w,2)

array([[1.40280301e-01, 9.03857692e-01, 5.35815131e-01, 3.58391981e-01,
        2.43418162e-02, 2.43342904e-02],
       [3.37370600e-03, 7.50261116e-01, 3.61339257e-01, 5.01366775e-01,
        4.23721405e-04, 9.40725121e-01],
       [6.92960750e-01, 4.50878979e-02, 3.30603187e-02, 3.36372142e-02,
        9.25633424e-02, 2.75369313e-01],
       [1.86576499e-01, 8.48144121e-02, 3.74363965e-01, 1.94585372e-02,
        8.53484957e-02, 1.34221000e-01]])

In [23]:
# Find the mean, min, max, standard deviation, variance of the latest array using np.mean()
print(np.mean(w),"\n",np.max(w),"\n",np.min(w),"\n",np.std(w),"\n",np.var(w))

0.44016245896496015 
 0.9699098521619943 
 0.020584494295802447 
 0.2852002868196039 
 0.08133920360198434


In [24]:
# Create two arrays of random integers between 0 to 10 one of size (3, 3) the other of size (3, 2)
c1=np.random.randint(0,10,(3,3),np.int64)
c2=np.random.randint(0,10,(3,2),np.int64)

In [25]:
# Perform a dot product on the two newest arrays you created
cd = np.dot(c1,c2)
print(cd)

[[108 111]
 [ 46  65]
 [ 96 107]]


In [26]:
# Create two arrays of random integers between 0 to 10 both of size (4, 3)
q1 = np.random.randint(0,10,(4,3),np.int64)
q2 = np.random.randint(0,10,(4,3),np.int64)

In [27]:
# Perform a hadamard product on the two newest arrays you created
qmard = np.multiply(q1,q2)
qmard

array([[ 7, 28, 14],
       [ 0, 56, 16],
       [ 0,  0, 24],
       [72, 42,  0]], dtype=int64)

In [28]:
# Perform a dot product on the two newest arrays you created # Error anticipated
qdaot = np.dot(q1,q2)

ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

In [29]:
# Take the latest two arrays, perform a transpose on one of them and then perform a dot product on them both
qdot = np.dot( q1,np.transpose(q2))
qdot

array([[ 49,  42,  30,  96],
       [135,  72,  50, 201],
       [ 68,  68,  24, 102],
       [105,  49,  16, 114]], dtype=int64)

In [30]:
# Create two arrays of random integers between 0 & 10 of the same shape and save them to variables
q3 = np.random.randint(0,10,5)
q4 = np.random.randint(0,10,5)

In [31]:
# Compare the two arrays with '>', '<=' and '==' 
print(q3>q4)
print(q3<=q4)
print(q3==q4)

[ True False  True False False]
[False  True False  True  True]
[False  True False  True False]


In [32]:
# Sort one of the arrays you just created in ascending order
np.sort(q3)

array([1, 6, 7, 8, 8])

In [33]:
# Sort the indexes of one of the arrays you just created
print(np.argsort(q3))

[4 1 3 0 2]


In [34]:
# Find the index with the maximum value in one of the arrays you've created
print(np.argmax(q3))

0


In [35]:
# Create an array with 10 evenly spaced numbers between 1 and 100
np.linspace(1,100,10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

In [36]:
# Find the indexes with the maximum values down the verticial axis of one of the arrays you created
np.argmax(q1,axis = 1)

array([2, 0, 1, 0], dtype=int32)

In [37]:
# Find the indexes with the minimum values across the horizontal axis of one of the arrays you created
np.argmin(q1,axis=0)


array([2, 0, 3], dtype=int32)